# .auto-version.config.toml
projects = [
    "packages/wal-core",
    "packages/wal-runtime",
    "packages/wal-cli",
]

major = ["feat"]
minor = ["feat"]
patch = ["fix", "perf", "refactor"]

# [fix-deps] # if only release github, don't need pypi
# repo-url = "https://github.com/D7x7z49/workflow-as-list.git"
